### ISSUE TITLE
Google API Error : 503

### ISSUE THREAD

**Issue by hpacleb3** [peterthehan/discord-emoji-log-bot#3]
I noticed that this happens quite often after a few days of the bot running.  After a simple google search, explanation would say that its because of the amount of requests being sent to the spreadsheet API. Are the rejected logs still being sent again ? or are they not recorded? Is there any fix for this?

```
Error: Google API error - [503] The service is currently unavailable.
  config: {
      url: "/values/'logs':append",
      method: 'post',
      params: [Object],
      data: '{"values":[["=\\"596578487209295872\\"","=\\"429863744361725985\\"","=\\"592743219599638666\\"",true,"2020-03-04T12:32:08.045Z"]]}',
      headers: [Object],
      baseURL: 'https://sheets.googleapis.com/v4/spreadsheets/1Bq4NipV7MJoUMQ5V75h1d75l0S4ZfHDJQS1umd7ILG0',
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'POST /v4/spreadsheets/1Bq4NipV7MJoUMQ5V75h1d75l0S4ZfHDJQS1umd7ILG0/values/%27logs%27:append?valueInputOption=USER_ENTERED&insertDataOption=OVERWRITE&includeValuesInResponse=true HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json;charset=utf-8\r\n' +
        'Authorization: Bearer ya29.c.Ko8BwAcy1QP8eZk5rsaE6GoWhLS6Ls9e6uHmuhwRxKn7MB_TMVjffXped-dGZbgmOSP7aDdVp-5NOlHpZzB-ptueyAZe5jLP6-IONN5OtNWKo-wzlfV6dJV5Hvf_dRPYQBDZhx3lYLXyoJ_FURgh_dglmTdEl3wXsUVHpv-AYCugTQCvUtwU2al6MCEuBVnoNdM\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Content-Length: 124\r\n' +
        'Host: sheets.googleapis.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      insecureHTTPParser: undefined,
      path: '/v4/spreadsheets/1Bq4NipV7MJoUMQ5V75h1d75l0S4ZfHDJQS1umd7ILG0/values/%27logs%27:append?valueInputOption=USER_ENTERED&insertDataOption=OVERWRITE&includeValuesInResponse=true',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    response: {
      status: 503,
      statusText: 'Service Unavailable',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    },
    isAxiosError: true,
    toJSON: [Function]
  }
}
```

**Comment by peterthehan** [comment]
5xx errors are issues with Google's servers. It looks like the strategy is to implement [exponential backoff](https://cloud.google.com/storage/docs/exponential-backoff) on the request. I'll look into this. And no, requests are only being tried once at the moment.

Does restarting the bot fix the issue? If so, for the time being, I suggest cycling the bot on a fixed period (maybe daily?).

**Comment by hpacleb3** [comment]
No restart is actually required, the bot will log again once its able to. Just unsure on how many # of logs gets dropped if the error appears since they just happen randomly and I once had multiple 503 errors (# of 503 errors = the # of logs dropped?).  Thanks!

**Comment by peterthehan** [comment]
Yeah as far as I'm aware, it should be 1 to 1 for errors to logs dropped.

This sort of unreliability is not great. I'll try to prioritize this.

**Comment by peterthehan** [comment]
Bot should now try five times before failing instead of just once. You might have to redo bot set up however, I kind of converted all my bots to "widgets" (the readme should be straightforward, let me know if it's not).

**Comment by hpacleb3** [comment]
Yeah the readme was fine and i got it up working for me now 
You only forgot to update the config.js part of the readme
![image](https://user-images.githubusercontent.com/53234009/76178323-ed08a200-61f1-11ea-9297-97fd379dadf0.png)

**Comment by peterthehan** [comment]
Whoops, thanks for catching that, I reverted the config to match the readme (I think it's easier to configure). If you already downloaded and setup the project, the only file that's changed was the `config.js` (you can just copy-paste the file contents to what you already have). Cheers!
